### ISSUE TITLE
需要nodejs哪个版本呢？

### ISSUE THREAD

**Issue by vhikd** [jsososo/QQMusicApi#1]
我用的8.12 安装好之后 无法获取到播放地址 返回的data是空的

**Comment by jsososo** [comment]
nodejs版本没问题的，播放地址为空是因为没有已登陆vip用户的cookie，这个我现在也很头疼，登陆绕不过去，cookie还要每天一更新，你可以访问一下 http://api.qq.jsososo.com/user/cookie 这里返回的 userCookie 是我存在服务器上的自己的 cookie

**Comment by vhikd** [comment]
鹅厂现在是必需登录 而且不登录很多歌曲不能听 我刚试了一下 确实是这样 这个就让人头疼了 没有用户信息获取不到音乐地址

**Comment by jsososo** [comment]
昨天发现客户端的cookie也可以拿来假装登陆，这样应该能降低一下更新频率
