### ISSUE TITLE
[QUESTION] Using not from China

### ISSUE THREAD

**Issue by fuk-github-hitler-rocks** [jsososo/QQMusicApi#10]
Hi. thanks for your project. I know, song url can't getting not from China, so I am interested in possibility self hosting. Any easy deploy hosting in China?

**Comment by jsososo** [comment]
Emm, to deploy hosting in China, you need to put on record to the goverment first but i guess foreigners may not be able to.   
I'm now deploying on https://api.qq.jsososo.com, you can use it if the number of requests is not large.

**Comment by zhoushoujian** [comment]
HongKong server needn't  put on record to the government . 
I have a question,  when nodejs direct visit https://api.qq.jsososo.com api, it will return '自己起一个 node 服务 这么难？？?'，why design this interceptor?

**Comment by jsososo** [comment]
hahahhaha，because i find someone often call my interface everytime，so i add a request limit middlewar to limit heavy ips, okhttp and other os system visit. You can check the rules in util/dataStatistics.js

**Comment by fuk-github-hitler-rocks** [comment]
Thanks for answer!
