### ISSUE TITLE
歌手详情接口某些mid报错

### ISSUE THREAD

**Issue by cloverzrg** [jsososo/QQMusicApi#107]
我遍历了一遍所有歌手详情页，这三个mid报错
/singer/desc?singermid=004U266W366wnO
/singer/desc?singermid=001fQGu53vtqsD
/singer/desc?singermid=002hAQrg1Fo0zH

**Comment by cloverzrg** [comment]
没人管的项目我就关掉算了

**Comment by jsososo** [comment]
抱歉，最近因为面试和工作等关系没什么时间更新，我会等有空的时候统一清理一遍issue的

2021年3月15日 上午10:05，朱润根 ***@***.******@***.***>> 写道：



没人管的项目我就关掉算了
