### ISSUE TITLE
现在响应拿到链接之后，复制到浏览器打开好像会在服务器上找不到？

### ISSUE THREAD

**Issue by Rainpler** [jsososo/QQMusicApi#115]
The requested URL '/C400002202B43Cq4V4.m4a' was not found on this server.

http://127.0.0.1:3300/song/urls?id=0039MnYb0qxYhV,004Z8Ihr0JIu5s
{
    "data": {
        "0039MnYb0qxYhV": "http://122.226.161.16/amobile.music.tc.qq.com/C400002202B43Cq4V4.m4a?guid=2796982635&vkey=A1CDF6B92C1707CF7AD88B551784C173AA3F43BB0A01877A1B9DE6E568B764F38E577905539B11D0E6ACCD78560D8FFC5C28765F951467AB&uin=1036791278&fromtag=66",
        "004Z8Ihr0JIu5s": "http://122.226.161.16/amobile.music.tc.qq.com/C4000012Ez0a1tFcOI.m4a?guid=2796982635&vkey=708AFCB1EFE1C3126213C581B91A953071766B546A3B010F4D6E4EDD2ADE480E9FB13B1A5DB520C3F261028F937405FA6DAAC464AF5A01DB&uin=1036791278&fromtag=66"
    },
    "result": 100
}

**Comment by jsososo** [comment]
你的代码是不是很久没更新过了，之前这里的链接逻辑处理过，现在应该是 ws 开头的一个域名

2021年5月27日 下午4:31，Rainpler ***@***.******@***.***>> 写道：



The requested URL '/C400002202B43Cq4V4.m4a' was not found on this server.

http://127.0.0.1:3300/song/urls?id=0039MnYb0qxYhV,004Z8Ihr0JIu5s
{
"data": {
"0039MnYb0qxYhV": "http://122.226.161.16/amobile.music.tc.qq.com/C400002202B43Cq4V4.m4a?guid=2796982635&vkey=A1CDF6B92C1707CF7AD88B551784C173AA3F43BB0A01877A1B9DE6E568B764F38E577905539B11D0E6ACCD78560D8FFC5C28765F951467AB&uin=1036791278&fromtag=66",
"004Z8Ihr0JIu5s": "http://122.226.161.16/amobile.music.tc.qq.com/C4000012Ez0a1tFcOI.m4a?guid=2796982635&vkey=708AFCB1EFE1C3126213C581B91A953071766B546A3B010F4D6E4EDD2ADE480E9FB13B1A5DB520C3F261028F937405FA6DAAC464AF5A01DB&uin=1036791278&fromtag=66"
},
"result": 100
}
