### ISSUE TITLE
希望能够获取QRC歌词

### ISSUE THREAD

**Issue by WXRIW** [jsososo/QQMusicApi#118]
目前接口只能获取到lrc歌词，时间轴精确到行，如果能获取到qrc精确到字的歌词就好了。

官方接口似乎是这个，我还没搞清楚：
https://c.y.qq.com/qqmusic/fcgi-bin/lyric_download.fcg?version=15&miniversion=82&lrctype=4&musicid=

感谢开发者！这个项目对我帮助很大！再次感谢！

**Comment by jsososo** [comment]
这个接口是哪里获取到的，我查了好久，web和h5都没找到这个接口，然后客户端因为编码或者其他不方便抓包的东西也没有找出来

**Comment by WXRIW** [comment]
https://github.com/xmcp/QRCD/blob/master/qrcd.py
45-50行，似乎获取的是qrc。

然后客户端抓包获取到的也是类似的，如：
https://c.y.qq.com/qqmusic/fcgi-bin/lyric_download.fcg?version=17&miniversion=77&musicid=E14CDA2D00FCBF32E9C72024D7DE99FEAC7BDB95C44B2959&songtype=0&timetag=0&transtimetag=0&romatimetag=0&lrctype=4

可能 `lrctype=4` 是关键。返回数据：
```
<!--
<command-lable-xwl78-qq-music>
<cmd value="1031" verson="4"><miniversion="1" /><result>0</result><reason>success</reason><uin>0</uin><check musicid="315148966" songtype="0"><downloadtag>1</downloadtag></check><lyric hidesearch="0" musicid="315148966" timetag="1624603093" scroll="4" urlhash="" encode="1" kt="1"><adoptuser id="0"><uin>0</uin></adoptuser><content type="file" mime="file" timetag="1624603093" filescroll="3"><![CDATA[91405C0313FF...............9DC3EB6748AD5F7DF935]]></contentts><contentroma type="file" mime="file" timetag="1624593267"><![CDATA[]]></contentroma></lyric></cmd>
</command-lable-xwl78-qq-music>
-->
```

想问下目前该项目用的api是哪个呀？谢谢开发者！

**Comment by jsososo** [comment]
了解了，原来是用这段被注释的xml返回的，我只看了浏览器啥也没有，然后也没找到哪儿用了这个接口，那我明白了，回头我再找找js的这个解密

2021年6月27日 下午8:18，XY Wang ***@***.******@***.***>> 写道：



https://github.com/xmcp/QRCD/blob/master/qrcd.py
45-50行，似乎获取的是qrc。

然后客户端抓包获取到的也是类似的，如：
https://c.y.qq.com/qqmusic/fcgi-bin/lyric_download.fcg?version=17&miniversion=77&musicid=E14CDA2D00FCBF32E9C72024D7DE99FEAC7BDB95C44B2959&songtype=0&timetag=0&transtimetag=0&romatimetag=0&lrctype=4

可能 lrctype=4 是关键。返回数据：




想问下目前该项目用的api是哪个呀？谢谢开发者！

**Comment by WXRIW** [comment]
谢谢啦！

**Comment by jsososo** [comment]
抱歉，很认真的看过，那个项目是通过调用 exe 文件运行再去解码的，这个的话这边就不好实现了，也搜不出其他什么方案

**Comment by WXRIW** [comment]
好的，谢谢，辛苦啦！很不错的项目！我尽可能在客户端实现解码吧。
