### ISSUE TITLE
你好，自己的cookie如何放在网站供其他人用呢？

### ISSUE THREAD

**Issue by liuyike233** [jsososo/QQMusicApi#12]
对node.js不是很了解，只会点php，请教一下哪个文件里存放cookie，谢谢作者

**Comment by jsososo** [comment]
![image](https://user-images.githubusercontent.com/25875263/74013042-9592ce80-49c6-11ea-9b00-44887dcc9538.png)
有一个 `/user/setCookie` 的接口，用 contentType 为 application/json 的 post 的请求就会把 cookie 记录到服务器上保存起来，然后我的项目里是有写死如果 uin 是我的 qq 号，那就存为全局共享的 cookie，这里你自己服务器的话部署的时候去 `/router/user.js` 文件里找到 setCookie 接口改一下就行。

另外这个 cookie 的有效期最近是只有一天，就是需要每天都更新，目前我是自己用一个 chrome 插件，[qqmusic-cookie-porter](https://github.com/jsososo/qqmusic-cookie-porter) ，装好后打开[https://y.qq.com/?forceUpdateCookie=1](https://y.qq.com/?forceUpdateCookie=1)会自动把cookie发送动服务器上然后再自动跳转（不加后面那个参数默认8小时内不会处理）如果你需要这个的话，到时候可以在 `/js/content.js` 里改一下请求和跳转的域名就可以了
