### ISSUE TITLE
查询接口报错

### ISSUE THREAD

**Issue by lengdidi** [jsososo/QQMusicApi#121]
![image](https://user-images.githubusercontent.com/48507792/125434759-3f0d4c4c-772d-49cf-8f6c-4df09e5081e2.png)

**Comment by Mamong** [comment]
看起来是查询结果为空？

**Comment by Mamong** [comment]
问题是const res = await axios(obj);这里抛出了404，也就是https://c.y.qq.com/soso/fcgi-bin/search_for_qq_cp 这个接口有问题了

**Comment by Mamong** [comment]
目前的解决办法是注释掉search.js 37行。

**Comment by lengdidi** [comment]
> 目前的解决办法是注释掉search.js 37行。

你那边也有这样的报错吗

**Comment by dancelion** [comment]
> 目前的解决办法是注释掉search.js 37行。

试了下搜索的几个接口好像都挂了 老哥的解决办法好像也不行

**Comment by Mamong** [comment]
@dancelion 接口没有挂，我刚在我自己的服务器上试了

**Comment by Mamong** [comment]
@lengdidi 原来的接口404了，注释掉，强制用备用的接口就可以，隔壁项目用的就是这个备用的

**Comment by iwxyi** [comment]
> 目前的解决办法是注释掉search.js 37行。

这个确实有用，把这个接口注释掉了

**Comment by liuer666** [comment]
备用接口是哪个呀

**Comment by jsososo** [comment]
最新版本已修复，抱歉拖了很久才去更新，最新版目前同时支持了 npm 使用
