### ISSUE TITLE
创建歌单接口和删除歌单接口失效了

### ISSUE THREAD

**Issue by junga98** [jsososo/QQMusicApi#127]
**创建歌单接口报错**

`{"result":200,"errMsg":"创建出错: no permission","err":{"code":2,"subcode":1004,"reportcode":1004,"msg":"no permission","dirid":0,"Cert":{"code":0,"data":{"msg":"","identify_url":""}}}}`

**删除歌单接口报错**
`{"result":200,"errMsg":"删除出错:  �����µ�¼","err":{"code":2,"msg":" �����µ�¼","notdelnum":0,"ids":""}}`

兄dei可以看一下bug在哪

**Comment by jsososo** [comment]
没有cookie吧，我试了一下是可以的

**Comment by junga98** [comment]
这就有点摸不着头脑了，已登录了，有cookie，因为收藏歌单这些接口都没问题。
