### ISSUE TITLE
为什么setCookie显示成功，但一看还是没有设置到？

### ISSUE THREAD

**Issue by A1ita99** [jsososo/QQMusicApi#145]
格式好像也没错呀
![福昕截屏20220320111240872](https://user-images.githubusercontent.com/49982403/159146450-3bd6cf84-6d48-4cde-99fb-e2ca33c0fe82.PNG)
![福昕截屏20220320111248282](https://user-images.githubusercontent.com/49982403/159146454-4b251f96-1f7f-4fe7-b8ad-a5d7781cc8de.PNG)
![福昕截屏20220320111258584](https://user-images.githubusercontent.com/49982403/159146458-9b8acc1c-1a61-40b2-b5f2-9c980bda88c8.PNG)

**Comment by ClackBunny** [comment]
请问怎么解决的

**Comment by A1ita99** [comment]
> 

不好意思，时间太长我也忘记了，但是我记得是可以设置成功的。你可以看看最近iusse open那里，作者回复了，不知道能不能解决你的问题。

**Comment by jsososo** [comment]
调用完 set 之后必须要再调用 get 接口获取 cookie
[粘贴的图形-2.tiff]

2023年4月19日 09:37，ClackBunny ***@***.***> 写道：



请问怎么解决的
