### ISSUE TITLE
关于部分无损返回404链接

### ISSUE THREAD

**Issue by xyuanmu** [jsososo/QQMusicApi#15]
因为有些无损返回的链接是404，然后我看了一下代码，在获取vkey时 `filename` 用的是 `mid`，而不是 `media_mid`，所以返回的链接是404，比如这首歌：https://api.qq.jsososo.com/song/url?id=003u9Xfg0KLHNF&type=flac
应该先通过 https://c.y.qq.com/v8/fcg-bin/fcg_play_single_song.fcg?songmid=003u9Xfg0KLHNF&platform=yqq&format=json 获取 `media_mid`，再用 `media_mid` 拼出 `filename` 才能获取到正确的vkey。
完整拼接：http://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg?g_tk=1722049047&loginUin=956581739&needNewCode=0&cid=205361747&uin=323&songmid=003u9Xfg0KLHNF&filename=F000002pcmA1DrDOG.flac&guid=999
这里 songmid=**003u9Xfg0KLHNF**，filename=F00**0002pcmA1DrDOG**.flac
不知道我表述的是否清楚哈

**Comment by jsososo** [comment]
是的，就是这样，重点就是 `songmid` 和 `filename` 里对应的两个 `id` 是不一样的，大部分情况下其实不需要额外获取 `media_mid` 的，这个字段往往会和 `mid` 一起返回的，就是调这个接口的时候再一起传过去就行了，我的 `/song/url` 接口里也是因为出现了404，所以后来新增了一个 `mediaId` 的入参

**Comment by xyuanmu** [comment]
> 是的，就是这样，重点就是 `songmid` 和 `filename` 里对应的两个 `id` 是不一样的，大部分情况下其实不需要额外获取 `media_mid` 的，这个字段往往会和 `mid` 一起返回的，就是调这个接口的时候再一起传过去就行了，我的 `/song/url` 接口里也是因为出现了404，所以后来新增了一个 `mediaId` 的入参

原来这样，增加 `mediaId` 后可以获取正确的链接的，谢谢回复
