### ISSUE TITLE
api安装出错

### ISSUE THREAD

**Issue by superBoyJack** [jsososo/QQMusicApi#16]
你好，今天我在尝试安装你的api服务，但是装不上，能帮忙看下么，非常感谢
` qqmusicapi@0.0.0 start /root/QQMusicApi
> node ./bin/www

/root/QQMusicApi/app.js:51
      ...req.query,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/QQMusicApi/bin/www:7:11)

npm ERR! Linux 3.10.0-1062.4.1.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! qqmusicapi@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the qqmusicapi@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the qqmusicapi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs qqmusicapi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls qqmusicapi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/QQMusicApi/npm-debug.log`

**Comment by jsososo** [comment]
升级一下node版本试试，应该是node 版本低了，不支持 es6 语法，我自己一般用的是 8.9.0

**Comment by superBoyJack** [comment]
好的，我升级后就可以了，接下来研究下你提供的半自动获取Cookie插件，万分感谢！！！

**Comment by jsososo** [comment]
嗯，那个的话记得在 `user.js` 文件 `setCookie` 接口，把里面有一个写死的企鹅号换成你自己的哈
