### ISSUE TITLE
/song/urls 接口无法获取歌曲播放链接

### ISSUE THREAD

**Issue by Fantasy1316** [jsososo/QQMusicApi#162]
已通过 `/user/setCookie` 成功设置cookie，也能够通过 `user/cokkie` 查看当前cookie是设置成功的，但是任无法获取歌曲播放链接。

- 请求参数
```javascript
  {
    songmid: "000cqnBA4eF1Jl"
  }
```

- 返回结果
```javascript
  {
    result: 100,
    data: {}
  }
```

**Comment by qheartq616** [comment]
同问题，发现是接口返回数据少了purl。源代码逻辑是发五次请求，没有purl就不管了，请问楼主有找到解决办法吗

**Comment by Fantasy1316** [comment]
> 同问题，发现是接口返回数据少了purl。源代码逻辑是发五次请求，没有purl就不管了，请问楼主有找到解决办法吗

没有解决，后来换了[网易云API](https://github.com/Binaryify/NeteaseCloudMusicApi)了

**Comment by jsososo** [comment]
建议先关注一下账号的 cookie 设置是否正常。purl 的获取存在一定不明原因的获取失败（因此有5次重试逻辑），但是如果全部失败可以考虑是否当前 cookie 本身就无法获取该歌曲的播放链接，包括但不限于，会员歌曲、仅限购买、歌曲下架

**Comment by qheartq616** [comment]
> 建议先关注一下账号的 cookie 设置是否正常。purl 的获取存在一定不明原因的获取失败（因此有5次重试逻辑），但是如果全部失败可以考虑是否当前 cookie 本身就无法获取该歌曲的播放链接，包括但不限于，会员歌曲、仅限购买、歌曲下架

cookie应该没问题的，调取需要cookie的/user/detail接口没有报错，我账号也是绿钻。
我把逻辑改成获取purl后才能进行下一步。。。然后代码循环了几百次都没获取到我就放弃了
经实验发现，重新登陆后再获取cookie并设置有概率能获取到purl

**Comment by qheartq616** [comment]
已解决，换成song/url（下载接口）即可
我不知道在线播放和下载有什么区别  但是就是实现了hhh
