### ISSUE TITLE
配置好一切后，传入会员Cookie也不能获取付费音质链接的解决办法

### ISSUE THREAD

**Issue by superBoyJack** [jsososo/QQMusicApi#17]
问题还原：
在我配置完并传入**Cookie**后，并没有像预料的那样获取到付费歌曲以及无损音质，在我细(暴)心(怒)排查后，发现我的**Cookie**里面**uin**一项也就是**QQ号**，神奇的在前面多了一个字母 “**o**” 。
好的，找到问题，接下来就好办了，用**postman**手动**post**自己修改后（去掉字母 “**o**” ）的**Cookie**，再测试就已经完美运行了，奈斯。
目前并不清楚是不是只有我个人出现了这个问题，貌似作者和其他使用者都挺正常的。

**Comment by w0ai1uo** [comment]
我就是不正常的啊，我绿钻lv8都不行，我去试试你这个看行不行

**Comment by jsososo** [comment]
在接收端增加了对 uin 字段的多余字母去除，应该没问题了哈
