### ISSUE TITLE
[求助] POST不了

### ISSUE THREAD

**Issue by NiTian1207** [jsososo/QQMusicApi#18]
POST提示
{"result":400,"errMsg":"自己起一个 node 服务 这么难？？?"}
我是在自己的服务器上搭建的

**Comment by jsososo** [comment]
额，可能跟你的请求的系统有关，你把 util/dataStatistics.js 里面这段话的 if 判断那里删掉就好了。这里是拦截了来自 okhttp 和 other 操作系统的请求

**Comment by zhoushoujian** [comment]
很奇怪,我在chrome控制台运行那行代码({ okhttp: true }['okhttp'] || { Other: true }["Other"]),返回结果都是["okhttp"], 也就是说, 只要不在本地调用接口,都会命中那个if,从而直接从中间件返回.
