### ISSUE TITLE
这些是不是都不能用了

### ISSUE THREAD

**Issue by wzhs** [jsososo/QQMusicApi#180]
这些是不是都不能用了，我看网页上很多接口的URL和参数都有变化

**Comment by qheartq616** [comment]
目前发现search/song song/urls user/refresh不能用，其他大部分还是没问题
而且前两个接口失效似乎都有解决方案

**Comment by CaptainRuby** [comment]
@qheartq616 什么解决方案呀

**Comment by qheartq616** [comment]
@CaptainRuby search/song在其他地方回复你了  song/urls用song/url代替  user/refresh用https://blog.csdn.net/qq_41813208/article/details/112646537代替  似乎需要jdk11  我没有尝试


> @qheartq616 什么解决方案呀

**Comment by mebest100** [comment]
> @CaptainRuby search/song在其他地方回复你了 song/urls用song/url代替 user/refresh用[https://blog.csdn.net/qq_41813208/article/details/112646537代替](https://blog.csdn.net/qq_41813208/article/details/112646537%E4%BB%A3%E6%9B%BF) 似乎需要jdk11 我没有尝试
> 
> > @qheartq616 什么解决方案呀

@qheartq616  search接口不能用了，有什么替代方案吗，你那个csdn链接已经失效了。

**Comment by qheartq616** [comment]
> > @CaptainRuby search/song在其他地方回复你了 song/urls用song/url代替 user/refresh用[https://blog.csdn.net/qq_41813208/article/details/112646537代替](https://blog.csdn.net/qq_41813208/article/details/112646537%E4%BB%A3%E6%9B%BF) 似乎需要jdk11 我没有尝试
> > > @qheartq616 什么解决方案呀
> 
> @qheartq616 search接口不能用了，有什么替代方案吗，你那个csdn链接已经失效了。

/search接口可以用呀  看看你的接口和传参？
csdn那个链接是用模拟浏览器做qq音乐自动登陆的，比较麻烦，建议还是找其他办法吧

**Comment by mebest100** [comment]
@qheartq616  确实用不了啊。我就一个很简单的请求 /search?key=黎明 ，直接返回400

**Comment by qheartq616** [comment]
> @qheartq616 确实用不了啊。我就一个很简单的请求 /search?key=黎明 ，直接返回400

试一下在body以json格式传参吧
