### ISSUE TITLE
腾讯调整了接口吗，[获取专辑信息]和[歌手介绍]获取不到数据，上周还能正常调

### ISSUE THREAD

**Issue by zhemozhiwangddd** [jsososo/QQMusicApi#198]
[获取专辑信息]获取不到数据。[歌手介绍]接口也没有singername
![1709524019562](https://github.com/jsososo/QQMusicApi/assets/77574663/a60df4e9-9f19-4a63-9457-24379159b0d2)
![66743c95839ccdf20230293e289f17b](https://github.com/jsososo/QQMusicApi/assets/77574663/92969904-5c77-42a9-831e-7560c41cbc17)

**Comment by zhemozhiwangddd** [comment]
看了下代码应该是下图页面有变化，数据解析不出来？前端一片白纸，自己慢慢研究下，希望有大佬能帮忙解答
![70c53212a72639cfb6d3de5753b5242](https://github.com/jsososo/QQMusicApi/assets/77574663/c30c66e5-b12c-4435-830d-1e2050df94f4)
![df31c074b2c5489b76b5475df1fc2c5](https://github.com/jsososo/QQMusicApi/assets/77574663/a16b7e8e-da82-4b24-b64c-e610942e05bb)
![5f7800432365df0a75a433bcfeb36d8](https://github.com/jsososo/QQMusicApi/assets/77574663/eb07a554-0be9-42d8-a82b-329a5d6aea5b)
![f30fb4047f6500328acead11cf5ea64](https://github.com/jsososo/QQMusicApi/assets/77574663/d4a17d39-1fc3-4351-9662-3dcb6d33368c)

**Comment by tsingfa** [comment]
我的解决方法是：参考[[musicapi](https://github.com/Superheroff/musicapi)](https://github.com/Superheroff/musicapi/blob/main/musicapi.py) 中的请求方法，然后修改其中的param（表单数据）和cookie，在审查元素中都有，实测可用。

**Comment by tsingfa** [comment]
补充一下，无法访问的原因很可能是因为爬取过频，导致短暂地被封ip了，过几天应该就好了，理想的爬取量一般为每周1-2w条

**Comment by zhemozhiwangddd** [comment]
> 补充一下，无法访问的原因很可能是因为爬取过频，导致短暂地被封ip了，过几天应该就好了，理想的爬取量一般为每周1-2w条

感谢老哥回答！我这边换过服务器也获取不了专辑数据，而且是自己的小项目用的，调用频率很低，应该不是被封锁ip了。
这两个接口源码都是cheerio直接爬取页面拿到的数据，而不是调用腾讯的接口，然而现在代码中请求获取到的页面没有原来的专辑信息数据，这是页面改成动态加载爬取不到了把，前端这块不太懂哈。
/album?albummid=002MAeob3zLXwZ 就这个接口，有空了慢慢摸索

**Comment by tsingfa** [comment]
自动回复邮件已经收到啦，我会尽快处理。:)

**Comment by tsingfa** [comment]
> > 补充一下，无法访问的原因很可能是因为爬取过频，导致短暂地被封ip了，过几天应该就好了，理想的爬取量一般为每周1-2w条
> 
> 感谢老哥回答！我这边换过服务器也获取不了专辑数据，而且是自己的小项目用的，调用频率很低，应该不是被封锁ip了。 这两个接口源码都是cheerio直接爬取页面拿到的数据，而不是调用腾讯的接口，然而现在代码中请求获取到的页面没有原来的专辑信息数据，这是页面改成动态加载爬取不到了把，前端这块不太懂哈。 /album?albummid=002MAeob3zLXwZ 就这个接口，有空了慢慢摸索

参看我的第一条回复的解决方法，我也不会前端那块的，我现在直接走的腾讯接口可以。

**Comment by zhemozhiwangddd** [comment]
> > > 补充一下，无法访问的原因很可能是因为爬取过频，导致短暂地被封ip了，过几天应该就好了，理想的爬取量一般为每周1-2w条
> > 
> > 
> > 感谢老哥回答！我这边换过服务器也获取不了专辑数据，而且是自己的小项目用的，调用频率很低，应该不是被封锁ip了。 这两个接口源码都是cheerio直接爬取页面拿到的数据，而不是调用腾讯的接口，然而现在代码中请求获取到的页面没有原来的专辑信息数据，这是页面改成动态加载爬取不到了把，前端这块不太懂哈。 /album?albummid=002MAeob3zLXwZ 就这个接口，有空了慢慢摸索
> 
> 参看我的第一条回复的解决方法，我也不会前端那块的，我现在直接走的腾讯接口可以。

感谢老哥，刚弄好专辑接口，试过可以调用。再找找歌手信息接口，暂时在qq音乐的页面上没找到

**Comment by tsingfa** [comment]
自动回复：来信已收到，谢谢！我将稍后查阅处理！
