### ISSUE TITLE
功能

### ISSUE THREAD

**Issue by liuyike233** [jsososo/QQMusicApi#2]
有没有方法可以下载无损音质的音乐

**Comment by jsososo** [comment]
目前还没有，我有空试一下



发自我的小米手机
在 xirihefeng <notifications@github.com>，2019年12月4日 20:48写道：

有没有方法可以下载无损音质的音乐

**Comment by jsososo** [comment]
最新的可以了，[/song/url?id=000tkk3s2C8YEv&type=flac](https://api.qq.jsososo.com/song/url?id=000tkk3s2C8YEv&type=flac) 接口试一下

**Comment by w0ai1uo** [comment]
不懂nodejs，不知道cookie在哪里添加呀，dalao
