### ISSUE TITLE
请问，怎么关闭高频检测

### ISSUE THREAD

**Issue by NiTian1207** [jsososo/QQMusicApi#20]
我写的程序的下载功能需要连续请求多次下载链接，但是会被拉黑

**Comment by jsososo** [comment]
app.js 里关于 dataHandle 的都注释掉，重启一下，就像这个

`app.use((req, res, next) => dataHandle.record(req, res, next));`

**Comment by NiTian1207** [comment]
> app.js 里关于 dataHandle 的都注释掉，重启一下，就像这个
> 
> `app.use((req, res, next) => dataHandle.record(req, res, next));`

感谢。
