### ISSUE TITLE
一点小建议

### ISSUE THREAD

**Issue by zhoushoujian** [jsososo/QQMusicApi#21]
我粗略的阅读了您的代码, 发现代码质量非常好, 对于几个地方,我有些疑问, 或者说也算是建议吧
**1.** 每次运行npm start的时候都会输出`node ./bin/www`, 然后就没有了. 这样开发者也许不知道服务器初始化完成了没有. 我觉得如果在'`debug('Listening on ' + bind);`' 后面加上 `console.log("server is running on ", addr.port)` 会更好.每次初始化完成都会打印监听的端口号,这样开发者既能知道服务器初始化完成,可以访问了,也能提示当前监听的端口

**2.** 关于logger, 我看用到了`const logger = require('morgan')`, 但是这日志仅是
> HTTP request logger middleware for node.js

如果开发或运维想查看服务器的运行log文件的话, 比如,检查服务器的响应结果,或者服务器运行过程中有没有报错等

**3.** 关于
> dataHandle[func](ip, type);
  res.send({
    result: 100,
    data: '就当成功了吧',
  })

我觉得写一个回调给dataHandle, 在回调里运行'`就当成功了`吧'可能会更严谨.

**4.** 文中多次出现类似这种连环取属性的操作`result.gedan.data.vec_gedan`, 严格意义上来讲是不严谨, 正确的写法应该是
`if(result && result.gedan && result.gedan.data && result.gedan.data.vec_gedan ){
...
} else {
console.log('give some tips')
}`
当然,我们可以写一个函数来判断对象是否具有这些多层属性

**5.** 最后一点, 是我个人的编程军规:` feedback.js` line 19
我是很反对这种写法的`console.log(val, this.data);`, 因为当别人看到这条log的时候,不知道这条log是什么意思,,只能看到变量的结果. 规范的写法应该是`console.log('feedback add val', val, "this.data", this.data);`, 这样的话,别人看到就知道这条log是feedback文件里的,在add方法里,打印的两个变量的含义分别是`value`和`this.data`. 尤其是在日志文件里检查log,非常有用

在下才疏学浅,没有过多研究和调试,如有误解,欢迎指正

**Comment by jsososo** [comment]
非常感谢，其实之前并没有接触过太多的node 项目，一些规范上确实有疏忽，像 logger 其实并没有用上（平时主要做前端，也没有做日志的习惯） 
另外开发中也有些匆忙，像第四点也是完全依赖接口返回不报错并格式永远正常的情况，第五点那个`console.log` 其实是应该要删掉的，往往是在本地开发调试的时候临时加上的哈哈哈，总之非常感谢，后续也会抽空进一步的优化

**Comment by zhoushoujian** [comment]
这个项目写的真的不错,之前在review的时候,有几个地方觉得好像有问题,结果调试的时候就被打脸了,有实践才有发言权. 另外,我写的一个项目也依赖于你这个项目: `https://github.com/zhoushoujian/miXingFeng` . 我没有开源后端代码.前端代码4万多行,后端8000多行. 我发现实际项目中,往往前端比较复杂,无论是从组件和逻辑的复用以及耦合度还是代码量,前端和后端都不是一个级别的.我们公司的项目也如此,前端代码30多万行,后端微服务代码加起来也没有10万行.

**Comment by zhoushoujian** [comment]
关于服务端日志, 我曾经写过一个包, 如果你有空, 可以看一下, 如果有好的建议,也可以提一下, 谢谢: https://github.com/zhoushoujian/beauty-logger 
关于日志,我不仅在服务端用到了,在hybird的app端也在使用基于这个的日志
