### ISSUE TITLE
可以不统计IP不

### ISSUE THREAD

**Issue by xsbb666** [jsososo/QQMusicApi#22]
可以不统计他人IP不，容易暴露别人的IP在网上呀

**Comment by jsososo** [comment]
额，一般来说，现在都是动态ip，本身安全泄漏隐私什么的情况本身不大，其次，统计的主要原因是为了了解服务的接口调用量并对一些高频的爬虫加上限制，毕竟本身已经是一个开源项目了，我并不想提供一个开源的api服务出来

**Comment by xsbb666** [comment]
如果高频使用会BAN多久呢

**Comment by jsososo** [comment]
一般是一天，对某些使用动态代理爬虫的是ip段封三天
