### ISSUE TITLE
/song/url seems doesn't work any more, can you confirm

### ISSUE THREAD

**Issue by zhoushoujian** [jsososo/QQMusicApi#25]
/song/url seems doesn't work any more, can you confirm

**Comment by jsososo** [comment]
i found it last night, but debugging locally no problem and only server-side cannot work. so i have no idea yet

**Comment by zhoushoujian** [comment]
I can reproduce on my localhost, if I provide you the relevant data, can you investigate for me?

**Comment by jsososo** [comment]
ok, i reproduce too. emmm

**Comment by zhoushoujian** [comment]
request url: 
"http://c.y.qq.com/base/fcgi-bin/fcg_music_express_mobile3.fcg?g_tk=1722049047&loginUin=863165094&needNewCode=0&cid=205361747&uin=323&songmid=003uqixR0MtCUw&filename=M500003uqixR0MtCUw.mp3&guid=2662239"

response: 
"{"code":104003,"cid":205361747,"errinfo":"merror","data":{"items":[{"songmid":"","filename":"","vkey":""}]}}"

feedback:
{
result: 400,
errMsg: "获取播放链接出错"
}

**Comment by zhoushoujian** [comment]
OK, that's fine.

**Comment by jsososo** [comment]
I just fixed it.

**Comment by NiTian1207** [comment]
不知道为什么还是获取失败

**Comment by jsososo** [comment]
Cookie 更新了嘛，需要绿钻 cookie 的

**Comment by zhoushoujian** [comment]
Verified, good job!
