### ISSUE TITLE
怎么样算高频请求接口啊

### ISSUE THREAD

**Issue by top-li** [jsososo/QQMusicApi#26]

**Comment by jsososo** [comment]
1分钟100次，10分钟500次，1小时2000次

**Comment by top-li** [comment]
啊

**Comment by top-li** [comment]
我请求应该没有这么夸张啊

**Comment by top-li** [comment]
我就拿那个推荐歌单数据，结果看打印数据的时候就说禁了

**Comment by top-li** [comment]
能不能网开一面，这一天好长啊




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jsososo"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上6:33
收件人: "jsososo/QQMusicApi"<QQMusicApi@noreply.github.com&gt;; 
抄送: "&amp;#x270E;&amp;#xFE4F; &amp;#x2133;&amp;#xE53;&amp;#x20AF;&amp;#x3395;&amp;#x2766;"<mxvsqjkfte@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jsososo/QQMusicApi] 怎么样算高频请求接口啊，我想写项目，结果被禁了一天/(ㄒoㄒ)/~~ (#26)





 
1分钟100次，10分钟500次，1小时2000次

**Comment by top-li** [comment]
能不能网开一面，这一天好长啊，我后面注意次数



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jsososo"<notifications@github.com&gt;; 
发送时间: 2020年4月23日(星期四) 晚上6:33
收件人: "jsososo/QQMusicApi"<QQMusicApi@noreply.github.com&gt;; 
抄送: "&amp;#x270E;&amp;#xFE4F; &amp;#x2133;&amp;#xE53;&amp;#x20AF;&amp;#x3395;&amp;#x2766;"<mxvsqjkfte@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [jsososo/QQMusicApi] 怎么样算高频请求接口啊，我想写项目，结果被禁了一天/(ㄒoㄒ)/~~ (#26)





 
1分钟100次，10分钟500次，1小时2000次

**Comment by jsososo** [comment]
乖乖等一天吧，或者自己在clone 走起一下服务也可啊

**Comment by top-li** [comment]
clone，启动服务可以把这个弄掉吗------------------ 原始邮件 ------------------
发件人: "jsososo"<notifications@github.com>
发送时间: 2020年4月23日(星期四) 晚上9:56
收件人: "jsososo/QQMusicApi"<QQMusicApi@noreply.github.com>;
抄送: "top-li"<mxvsqjkfte@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [jsososo/QQMusicApi] 怎么样算高频请求接口啊 (#26)




 
乖乖等一天吧，或者自己在clone 走起一下&#x670D;务也可啊
 
&mdash;

**Comment by top-li** [comment]
额，原来还可以这样。。。
