### ISSUE TITLE
[Feature] 希望一个获取下载链接时重定向的功能

### ISSUE THREAD

**Issue by 17665347409** [jsososo/QQMusicApi#29]
## 描述
比如给一个参数isRedirect
/song/url?id=002Nn2nE0Hu7WM&isRedirect=1
在请求时当isRedirect=1时重定向到歌曲的下载链接
## 功能预期
请求/song/url?id=mid&isRedirect=1 =>判断当isRedirect=1 => 重定向到[歌曲下载链接](http://122.226.161.16/amobile.music.tc.qq.com/M500002Nn2nE0Hu7WM.mp3?guid=6025702&vkey=8516850702B797E75B092B5DBE2E967825017FF868DF41D8BDB0DC83C0EC26A2E898A436FF4BB8F8697EAC9D725B371DF0171CC7C650C846&uin=1899&fromtag=66)

**Comment by jsososo** [comment]
可以，我回头整一下

**Comment by jsososo** [comment]
最新版已添加
