### ISSUE TITLE
一首歌的问题

### ISSUE THREAD

**Issue by steven7851** [jsososo/QQMusicApi#3]
关键词: 如寄 - 萧忆情Alex
https://api.qq.jsososo.com/song/find?key=%E5%A6%82%E5%AF%84%20-%20%E8%90%A7%E5%BF%86%E6%83%85Alex
得到`songmid = 0001bB2k2wPvxW`后
https://api.qq.jsososo.com/song/urls?id=0001bB2k2wPvxW 返回的歌曲网址可正常播放
https://api.qq.jsososo.com/song/url?id=0001bB2k2wPvxW 返回的歌曲网址下载时回应404

**Comment by jsososo** [comment]
改了一下接口，刷新一下文档，现在这个接口再接受一个可选的 `mediaId` 参数，为其他接口中返回的 `strMediaId`，这首歌对应的接口获取url改为 (https://api.qq.jsososo.com/song/url?id=0001bB2k2wPvxW&mediaId=004dPgVk2IHnGf)[https://api.qq.jsososo.com/song/url?id=0001bB2k2wPvxW&mediaId=004dPgVk2IHnGf] 。这两个参数一般是收费歌曲不同，我自己都是拿周杰伦测试的，不传也没有这个问题，不知道为什么，有点迷
