### ISSUE TITLE
接口返回 {"result":400,"errMsg":"自己起一个 node 服务 这么难？？?"}

### ISSUE THREAD

**Issue by ellyliang** [jsososo/QQMusicApi#35]
koa搭的服务，已经起来了，本地用的是127.0.0.1:5000去访问的页面。

通过koa-request去请求你提供的接口，但是返回 {"result":400,"errMsg":"自己起一个 node 服务 这么难？？?"}，请问怎么解决呢？

![image](https://user-images.githubusercontent.com/4658035/81031483-fabf6880-8ebe-11ea-8b26-7f50f893a0b1.png)

![image](https://user-images.githubusercontent.com/4658035/81031504-090d8480-8ebf-11ea-9197-d5cc30da9783.png)

**Comment by 251205668** [comment]
axios它不香吗

**Comment by 17665347409** [comment]
尝试把util/dataStatistic中这一段注释掉
![image](https://user-images.githubusercontent.com/34836531/81265311-7531e900-9075-11ea-8bd1-704da684288c.png)
