### ISSUE TITLE
用git部署到服务器上，获取下载连接总是返回400错误

### ISSUE THREAD

**Issue by Tiamoupao** [jsososo/QQMusicApi#40]
用/song/url返回的总是400错误
用/song/urls直接就报错
(node:4660) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at reqFun (C:\Program\QQMusicApi\routes\song.js:146:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getUrls (C:\Program\QQMusicApi\routes\song.js:152:5)
(node:4660) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
想问问到底是什么问题

**Comment by jsososo** [comment]
这个是接口数据统计那里的报错，好像现在新的项目都会报错，我等等尽量抽空看看，你也可以先把 app.js 里和 dataHandle 相关的代码都注释掉

**Comment by Tiamoupao** [comment]
好的好的，谢谢了

**Comment by jsososo** [comment]
最新版问题已修复

**Comment by Tiamoupao** [comment]
老哥稳！！不过你删掉20191211这个文件的时候把父文件夹record也删了

**Comment by jsososo** [comment]
啊，我是没删掉的，应该是这个文件夹下没有文件了，git就把它弄没了，我再提交一个补上去的吧
