### ISSUE TITLE
git 部署后部分router报错

### ISSUE THREAD

**Issue by lzx19951022** [jsososo/QQMusicApi#42]
您好，我尝试在nas和电脑端克隆项目后使用npm start 命令运行，song/find 等几个get 都会报错，刚好就是需要这几个接口，我刚学node js，还比较小白，不知道怎么解决这个问题。。node版本是12.14.
![image](https://user-images.githubusercontent.com/35286852/84845344-ffab3680-b07e-11ea-822e-01528f1fe6d1.png)

**Comment by jsososo** [comment]
有设置好 cookie 和账号嘛，把报错信息发一下看看

**Comment by lzx19951022** [comment]
完全保持了默认的设置，没有设置自己的账号，报错信息如下：(node:159516) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at reqFun (E:\qqmusicapi\routes\song.js:146:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getUrls (E:\qqmusicapi\routes\song.js:152:5)
(node:159516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:159516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by lzx19951022** [comment]
完全保持了默认的设置，没有设置自己的账号，报错信息如下
`(node:159516) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at reqFun (E:\qqmusicapi\routes\song.js:146:22)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async getUrls (E:\qqmusicapi\routes\song.js:152:5)
(node:159516) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:159516) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by jsososo** [comment]
那不行的，这个接口是必须依赖登陆账号 cookie 的，可以再去看下文档那里

**Comment by lzx19951022** [comment]
我可以通过fetch之类的post一个cookie就可以是咩

**Comment by jsososo** [comment]
可以的，只要是 post 就行，不过要先把对应的账号设置上，不然不会默认设置成全局的 cookie

**Comment by lzx19951022** [comment]
按照你的提示post cokkie之后不再报错了，感谢!
