### ISSUE TITLE
如何自动更新 cookies

### ISSUE THREAD

**Issue by PeterDing** [jsososo/QQMusicApi#44]
我是通过 https://y.qq.com/ 登录 qq 来获取 cookies 的。对于获取音频链接，`qqmusic_key` 应该是关键，但是这个值只有一天的有效性，过期后无法再获取 flac 的链接。
请问我该如何自动更新 cookies，而不需要每天都登录一次再手动添加 cookies。

**Comment by jsososo** [comment]
这个我也暂时没有办法，现在最多也是用一个chrome 插件 https://github.com/jsososo/qqmusic-cookie-porter，但是每天还是必须要跑到qq音乐官网登陆一下，有过利用chrome无头模式的想法，但是一直没空去尝试，主要麻烦的还是登陆那一块
