### ISSUE TITLE
在用户歌单里 没有找到 “我喜欢” 的这个歌单

### ISSUE THREAD

**Issue by xsbb666** [jsososo/QQMusicApi#48]
在用户歌单里 没有找到 “我喜欢” 的这个歌单 只能看到自建歌单

**Comment by jsososo** [comment]
我喜欢只能通过 /user/detail 这个接口获取

**Comment by necan** [comment]
@jsososo 并没返回“我喜欢”歌单的数据
![image](https://user-images.githubusercontent.com/25315125/88476288-c7462480-cf69-11ea-8392-398fde28cf74.png)
