### ISSUE TITLE
获取榜单详情接口 - 参数问题

### ISSUE THREAD

**Issue by shichunlei** [jsososo/QQMusicApi#5]
请求参数：
pageNo 应该是页码
pageSize 应该才是每页条数

返回参数：
rankType：4 代表新歌

**Comment by jsososo** [comment]
昂，是的，这里有问题，非常感谢，我有空更新一下

**Comment by shichunlei** [comment]
榜单详情里的歌曲列表没有songmid字段啊，只有songid字段。怎么通过songid获取歌曲信息？

**Comment by jsososo** [comment]
这里songmid 缺失是我在转换的时候漏掉了，我稍后补上，songid其实挺弱的，大部分接口都是靠songmid去获取信息

**Comment by jsososo** [comment]
发现了，原来列表里的都是一些最简单的字段，现在从鹅厂那边换了一个字段取数据，这里的数据基本都全了，可以看下哈

**Comment by shichunlei** [comment]
改过之后的接口返回的歌曲列表中rank相关字段（rank、rankType、rankValue等）不见了呢。

**Comment by jsososo** [comment]
我把两边字段合并了，现在应该可以了

**Comment by shichunlei** [comment]
分类ID为 26 热歌榜、67 听歌识曲榜、所有地区榜、所有特色榜、部分全球榜等并没有添加上歌曲详情的字段，不知道是怎么回事？

**Comment by jsososo** [comment]
emmmm，原因找到了，处理起来有点麻烦，首先我所有的周度时间排行榜，传过去的时间都是当前周度，比如这周是 2019_51，但是各榜世纪的时间并不是本周，大部分都是上周 2019_50，有部分榜单（特别是全球榜中的一些），可能是更早的一些周度，他本身是能返回榜单里歌曲大致信息的一些数据，就是包含 rank、rankType 那些，但是详细信息列表是空的，我再想想办法

**Comment by jsososo** [comment]
我对`/top`和`/top/category`这两个接口都做了改造，发现了移动端的一个新接口，现在建议将`/top/category` 中返回了 `period` 字段，传到 `/top`里，不传也没事，但是可能会导致 node 要调两次接口，返回速度慢
