### ISSUE TITLE
获取下载链接错误。

### ISSUE THREAD

**Issue by RealHeart** [jsososo/QQMusicApi#56]
访问/song/url 返回{"result":400,"errMsg":"获取播放链接出错"}
访问/song/urls 后台报错
(node:29611) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at reqFun (/www/node/QQMusicApi/routes/song.js:154:22)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async getUrls (/www/node/QQMusicApi/routes/song.js:160:5)
(node:29611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jsososo** [comment]
有设置过cookie 信息嘛，提供一下歌曲id ？

2020年8月19日 下午9:55，RealHeart <notifications@github.com<mailto:notifications@github.com>> 写道：



访问/song/url 返回{"result":400,"errMsg":"获取播放链接出错"}
访问/song/urls 后台报错
(node:29611) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
at reqFun (/www/node/QQMusicApi/routes/song.js:154:22)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async getUrls (/www/node/QQMusicApi/routes/song.js:160:5)
(node:29611) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:29611) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by haanico** [comment]
问下作者，好像现在必须要绿钻的cookie,普通的不行，刚开绿钻试下cookie就成功了。  不是绿钻不能用吗

**Comment by jsososo** [comment]
之前应该非绿钻的cookie 只能获取非绿钻也能听的歌

2020年8月28日 下午2:02，haanico <notifications@github.com<mailto:notifications@github.com>> 写道：



问下作者，好像现在必须要绿钻的cookie,普通的不行，刚开绿钻试下cookie就成功了。 不是绿钻不能用吗
