### ISSUE TITLE
请问怎么从推荐歌单找到歌曲的songmid,文档里没写啊

### ISSUE THREAD

**Issue by mebest100** [jsososo/QQMusicApi#57]
请问怎么从推荐歌单recommend/playlist找到歌曲的songmid,文档里没写啊

**Comment by jsososo** [comment]
通过歌单id去调歌单详情

2020年8月28日 下午8:25，mebest100 <notifications@github.com<mailto:notifications@github.com>> 写道：



请问怎么从推荐歌单recommend/playlist找到歌曲的songmid,文档里没写啊
