### ISSUE TITLE
为什么把接口api部署在本地：调用时也会报错“你是不是接口访问次数太多了”，这个怎么破？

### ISSUE THREAD

**Issue by mebest100** [jsososo/QQMusicApi#58]
为什么把接口api部署在本地：调用时也会报错“你是不是接口访问次数太多了”，这个怎么破？

![image](https://user-images.githubusercontent.com/11530991/91629224-a73ad280-e9f9-11ea-9835-fc6048b2b71d.png)

**Comment by mebest100** [comment]
然后直接访问又报404，我就搞不明白了：接口调用方式难道不是ip+端口+接口路径吗？

![image](https://user-images.githubusercontent.com/11530991/91630368-7e1f3f80-ea03-11ea-8e78-b3b1e0e4e09a.png)

**Comment by jsososo** [comment]
路径里没有 music，调用次数过多的可以把 app.js 里和 dataHandle 相关的注释掉，或者给对应的ip 加白名单

2020年8月29日 下午2:26，mebest100 <notifications@github.com<mailto:notifications@github.com>> 写道：



然后直接访问又报404，我就搞不明白了：接口调用方式难道不是ip+端口+接口路径吗？

[image]<https://user-images.githubusercontent.com/11530991/91630368-7e1f3f80-ea03-11ea-8e78-b3b1e0e4e09a.png>
