### ISSUE TITLE
歌曲信息接口 /song 批量获得

### ISSUE THREAD

**Issue by Frozenmad** [jsososo/QQMusicApi#6]
您好，非常棒的项目！

但是我发现/song这一接口的扩展性不是很好，不能批量获得多个mid的歌曲信息。请问能否完善此接口？十分感谢！

**Comment by jsososo** [comment]
ok，我有空加一个 /songs 的接口吧

**Comment by Frozenmad** [comment]
感谢~ 以及期待！

**Comment by jsososo** [comment]
[/song/batch?songmids=001PLl3C4gPSCI,0039MnYb0qxYhV](http://api.qq.jsososo.com/song/batch?songmids=001PLl3C4gPSCI,0039MnYb0qxYhV)，新增了这个接口，试一下哈

**Comment by Frozenmad** [comment]
暂时没什么问题~ 感谢添加！
