### ISSUE TITLE
无法获取音乐链接 已设置vipcookie 测试接口同无法使用

### ISSUE THREAD

**Issue by RealHeart** [jsososo/QQMusicApi#60]
https://api.qq.jsososo.com/song/url?songmid=0022RXDU1tLsYU

**Comment by jsososo** [comment]
参数穿错了，key 名是 id

2020年10月4日 下午9:55，RealHeart <notifications@github.com<mailto:notifications@github.com>> 写道：



https://api.qq.jsososo.com/song/url?songmid=0022RXDU1tLsYU
