### ISSUE TITLE
/singer/list 这个接口客户端请求301，这个也需要用户登录的cookie吗？

### ISSUE THREAD

**Issue by neugaojin** [jsososo/QQMusicApi#61]

**Comment by jsososo** [comment]
应该是不需要的，301不是重定向嘛

2020年10月8日 下午10:04，碰碰凉 <notifications@github.com<mailto:notifications@github.com>> 写道：

**Comment by neugaojin** [comment]
嗯嗯 是我没注意，用的http, 换成https之后 一直是400，我看文档里面说的是node 捕获的未知异常,不太清楚是为什么...

大佬我是做Android的，自己没事写了一个QQ音乐的客户端:https://github.com/neugaojin/SEMusic

一直发愁爬QQ音乐接口的事情，不知道方不方便加个微信，一起搞一个开源的学习项目

我的微信: gaojin19950823
