### ISSUE TITLE
请求播放地址接口返回304，返回data为空（本地部署，cookie已经添加），什么原因呢

### ISSUE THREAD

**Issue by mebest100** [jsososo/QQMusicApi#62]
请求播放地址接口返回304，返回data为空（本地部署，cookie已经添加），什么原因呢

![image](https://user-images.githubusercontent.com/11530991/96810929-55895400-144e-11eb-9167-900310a289ac.png)

**Comment by jsososo** [comment]
浏览器钩上 disable cache，走了浏览器的缓存，然后修改config 里的qq号了嘛

2020年10月22日 上午10:08，mebest100 <notifications@github.com<mailto:notifications@github.com>> 写道：



请求播放地址接口返回304，返回data为空（本地部署，cookie已经添加），什么原因呢

[image]<https://user-images.githubusercontent.com/11530991/96810929-55895400-144e-11eb-9167-900310a289ac.png>

**Comment by jjsisjjz** [comment]
可能是账号不是绿钻吧，我之前的也是这样，付费的返回不了
