### ISSUE TITLE
怎么获取音乐链接不行啊，还有一些其他接口，是要设置cookie才能使用吗

### ISSUE THREAD

**Issue by jjsisjjz** [jsososo/QQMusicApi#64]
求助

**Comment by jsososo** [comment]
是的，很多接口是需要cookie的

2020年10月28日 下午11:31，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



求助

**Comment by jjsisjjz** [comment]
为什么设置cookie不了报错500

**Comment by jjsisjjz** [comment]
设置好了，但是为什么返回的是空值

**Comment by jjsisjjz** [comment]
成功返回值了

**Comment by jsososo** [comment]
请求参数不对吧，参考文档，content-type: application/json

2020年10月29日 下午10:09，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



为什么设置cookie不了报错500

**Comment by jjsisjjz** [comment]
用那个播放器为什么调用都失败了，报错404

**Comment by jsososo** [comment]
nginx配置了嘛，需要做代理的，nginx 或者 Charles

2020年10月30日 下午2:39，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



用那个播放器为什么调用都失败了，报错404

**Comment by Buttonss** [comment]
貌似服务器炸了

**Comment by jjsisjjz** [comment]
![Uploading 1604069007166.jpg…]()
求助

**Comment by jjsisjjz** [comment]
nginx配置了但调用接口还是会报404

**Comment by jsososo** [comment]
贴一下你的nginx 配置，你钱一张图挂了

2020年10月31日 下午1:42，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



nginx配置了但调用接口还是会报404

**Comment by jjsisjjz** [comment]
apiMix报错

**Comment by jjsisjjz** [comment]
其他的接口都跨域成功了，就这个apiMix报错，而且还是没有出来，一直都是前端那个界面，什么都没有

**Comment by jsososo** [comment]
一直都是前端界面是什么意思，nginx和apiMix那个项目的config 配置是对的嘛

2020年10月31日 下午7:18，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



其他的接口都跨域成功了，就这个apiMix报错，而且还是没有出来，一直都是前端那个界面，什么都没有

**Comment by jjsisjjz** [comment]
就是界面里什么都没有但是能登陆，和设置cookie 但就这些能用的，其他的都不能用，搜索都不能，话说这个apiMix是哪个项目的，前端吗，这个apiMixnot found 问题怎么解决

**Comment by jjsisjjz** [comment]
我只设置了nginx的配置，vue前端也要配置跨域吗

**Comment by jsososo** [comment]
Nginx 的配置包括 apiMix 了嘛，apiMix 里面也有接口转发的部分，那个项目的 config.js 里也有配置了转发的地址

2020年10月31日 下午10:43，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



我只设置了nginx的配置，vue前端也要配置跨域吗

**Comment by jjsisjjz** [comment]
那个，apiMix的proxy_pass是什么，没找到

**Comment by jjsisjjz** [comment]
啊这，我懂了，作者你还有个后端啊，刚才翻了一下你的项目，发现里面还有一个

**Comment by jjsisjjz** [comment]
https://github.com/jsososo/NeteaseMusic，作者为什么这里面只有三个api github的地址，有点误导我了

**Comment by jjsisjjz** [comment]
https://github.com/jsososo/MixMusicApi
还少了这个难怪

**Comment by jsososo** [comment]
因为平时的更新记录都是为了给用户看的，所以有变更啥的都写到about里了，然后readme平时就没怎么更新了

2020年11月1日 下午1:30，啊啊啊啊啊 <notifications@github.com<mailto:notifications@github.com>> 写道：



https://github.com/jsososo/MixMusicApi
还少了这个难怪

**Comment by jjsisjjz** [comment]
OK，成功运行了

**Comment by jjsisjjz** [comment]
啊这，为什么没声音

**Comment by jjsisjjz** [comment]
浏览器报错Cannot read property lyric of undefined
