### ISSUE TITLE
获取榜单列表失败

### ISSUE THREAD

**Issue by GITHUBXIONGXINOG** [jsososo/QQMusicApi#66]
请教一下作者,自己搭建在服务器上通过/top/category获取榜单列表失败是怎么回事?
通过/top可以成功访问
![image](https://user-images.githubusercontent.com/43228067/99180700-929de900-2763-11eb-96a8-d2c3ef1945cb.png)
但通过/top/category访问失败
![image](https://user-images.githubusercontent.com/43228067/99180805-7484b880-2764-11eb-9b63-ee03f6b00bbc.png)
它提示 TypeError: Cannot read property 'data' of undefined
![image](https://user-images.githubusercontent.com/43228067/99180832-a39b2a00-2764-11eb-9585-006001e6a128.png)
我按照提示来到top.js,但并不知道之后该怎么操作了,有空闲的话能帮忙看一下吗?感谢

**Comment by jsososo** [comment]
应该是这个接口依赖cookie信息

2020年11月15日 下午5:25，GITHUBXIONGXINOG <notifications@github.com<mailto:notifications@github.com>> 写道：



请教一下作者,自己搭建在服务器上通过/top/category获取榜单列表失败是怎么回事?
通过/top可以成功访问
[image]<https://user-images.githubusercontent.com/43228067/99180700-929de900-2763-11eb-96a8-d2c3ef1945cb.png>
但通过/top/category访问失败
[image]<https://user-images.githubusercontent.com/43228067/99180805-7484b880-2764-11eb-9b63-ee03f6b00bbc.png>
它提示 TypeError: Cannot read property 'data' of undefined
[image]<https://user-images.githubusercontent.com/43228067/99180832-a39b2a00-2764-11eb-9585-006001e6a128.png>
我按照提示来到top.js,但并不知道之后该怎么操作了,有空闲的话能帮忙看一下吗?感谢

**Comment by GITHUBXIONGXINOG** [comment]
十分感谢您的帮助,修改cookie信息后成功使用
