### ISSUE TITLE
使用axios解决‘Access-Control-Allow-Origin’跨域

### ISSUE THREAD

**Issue by chung4real** [jsososo/QQMusicApi#68]
// PR鉴权失败 只好issues了
// 这是因为http请求头部没有进行允许跨域导致的，打开后端服务的app.js文件，在路由配置前添加以下代码
app.all('*', function(req, res, next) {
    res.header("Access-Control-Allow-Origin", "*");
    res.header("Access-Control-Allow-Headers", "X-Requested-With,Content-Type");
    res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
    next();
})

**Comment by jsososo** [comment]
额，因为我是在自己服务器上也有部署，不希望被他人直接用来调用，所以没有加允许跨域（只有一个设置cookie的加了

2020年12月7日 上午12:17，chung4real <notifications@github.com<mailto:notifications@github.com>> 写道：



// PR鉴权失败 只好issues了
// 这是因为http请求头部没有进行允许跨域导致的，打开后端服务的app.js文件，在路由配置前添加以下代码
app.all('', function(req, res, next) {
res.header("Access-Control-Allow-Origin", "");
res.header("Access-Control-Allow-Headers", "X-Requested-With,Content-Type");
res.header("Access-Control-Allow-Methods","PUT,POST,GET,DELETE,OPTIONS");
next();
})

**Comment by chung4real** [comment]
好吧😂
