### ISSUE TITLE
cookie已正确设置，也是用的本地搭建的服务，获取到的音乐链接有时候无法播放

### ISSUE THREAD

**Issue by Yooye** [jsososo/QQMusicApi#69]
![image](https://user-images.githubusercontent.com/9428679/102056704-b36f6200-3e27-11eb-93c7-e4b5d03fe64b.png)

提示信息：The requested URL '/C4000012Ez0a1tFcOI.m4a' was not found on this server.

官网的测试链接也是类似问题，是大佬的服务挂了吗？通过什么方式可以避免这种情况？

**Comment by xiaou66** [comment]
将 http://122.226.161.16/amobile.music.tc.qq.com/ 替换成 http://122.226.161.16/amobile.music.tc.qq.com/ 即可播放

**Comment by Yooye** [comment]
好的，替换后可以播放了，多谢

**Comment by jsososo** [comment]
问题已修复了，原先因为ip域名可以避开跨域问题，所以一直采用ip域名，不过现在ip域名也加跨域限制了，所以就用回接口返回的内容了

2020年12月15日 上午9:48，Yooye Lu <notifications@github.com<mailto:notifications@github.com>> 写道：



好的，替换后可以播放了，多谢
