### ISSUE TITLE
请教设置cookie的方法

### ISSUE THREAD

**Issue by kozhnpc** [jsososo/QQMusicApi#7]
您好，首选感谢您的开源分享。有个问题想请教一下，我看源码里面有一个使用POST方法在body中传入cookie的方式来设置全局的cookie，我用PostMan试着传入了QQ音乐的cookie的值，但是每次都会返回	

<h1>Cannot read property 'split' of undefined</h1>
	<h2></h2>
	<pre>TypeError: Cannot read property 'split' of undefined
    at router.post (/root/git/QQMusicApi/routes/user.js:18:8)

应该是传入的参数格式有问题，所以想请问一下，在body中传入的格式是什么样的呀（这方面我接触的少，不太懂，勿见怪）  我在传参的时候是这么做的  ： 在body中添加： pgv_pvid=XXXX; ts_uid=XXXX ...

**Comment by jsososo** [comment]
![image](https://user-images.githubusercontent.com/25875263/71455261-2a52bb80-27cf-11ea-8a92-7a6a6d47fa8b.png)

body中写成 json 的格式，然后选择 application/json 最好不要随便调我服务器上的这个接口哈，不然我可能就听不了歌了

**Comment by kozhnpc** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/25875263/71455261-2a52bb80-27cf-11ea-8a92-7a6a6d47fa8b.png)
> 
> body中写成 json 的格式，然后选择 application/json 最好不要随便调我服务器上的这个接口哈，不然我可能就听不了歌了

谢谢啦，我是设置自己服务器上的cookie，放心，不会动你这个服务器上的cookie的，再次感谢。

**Comment by sxyugao** [comment]
建议写到文档里去。。
