### ISSUE TITLE
为什么我的调用接口显示跨域

### ISSUE THREAD

**Issue by jing-jiu** [jsososo/QQMusicApi#71]
为什么我的调用接口显示跨域

**Comment by jing-jiu** [comment]
![image](https://user-images.githubusercontent.com/65278479/102233729-8906cd00-3f2b-11eb-9ea1-660ec6810d2f.png)

**Comment by jsososo** [comment]
因为我本来就没有全局加上允许跨域，主要我有在线版的服务，但是不希望被他人使用就没加，自己需要可以在app.js 全局加上

**Comment by jing-jiu** [comment]
你好那请问咋加呢
