### ISSUE TITLE
希望增加对一些老接口的支持

### ISSUE THREAD

**Issue by ShuYuMo2003** [jsososo/QQMusicApi#75]
比如 ： https://y.qq.com/n/yqq/song2/113/2999034.html?ADTAG=erweimashare&channelId=10036163&openinqqmusic=1

可能甚至QQ音乐web端都不支持……，在QQ音乐客户端搜索 `女儿情 吴静 伴奏`

![image](https://user-images.githubusercontent.com/60262785/103160894-3247a000-4815-11eb-861f-4abea97f4f6c.png)

元旦晚会有一个大哥要唱…………

**Comment by jsososo** [comment]
如果web端不支持的，这个可能有点难，因为现在的接口都是基于web端的，app端的传输都是加密或者私有编码

2020年12月27日 上午7:29，YuMo Shu <notifications@github.com<mailto:notifications@github.com>> 写道：



比如 ： https://y.qq.com/n/yqq/song2/113/2999034.html?ADTAG=erweimashare&channelId=10036163&openinqqmusic=1

可能甚至QQ音乐web端都不支持……，在QQ音乐客户端搜索 女儿情 吴静 伴奏

[image]<https://user-images.githubusercontent.com/60262785/103160894-3247a000-4815-11eb-861f-4abea97f4f6c.png>

元旦晚会有一个大哥要唱…………
