### ISSUE TITLE
是否有获取播放历史的Api

### ISSUE THREAD

**Issue by sylvaner-h** [jsososo/QQMusicApi#77]
rt.

迫于QQ的年终统计只显示Top5，想获取更多听歌记录

**Comment by jsososo** [comment]
之前有尝试过，后来发现桌面端手机端的app都是只获取本地的听歌记录，所以后来也就没有找了

**Comment by sylvaner-h** [comment]
在现在的版本中，App/PC端可以同步最近播放的500首歌；
我尝试用Fiddler抓包但是没有成功；

**Comment by jsososo** [comment]
我这边Mac客户端和网页版的听歌记录同步不到手机上，挠头

2021年1月13日 上午9:36，Sylvaner <notifications@github.com<mailto:notifications@github.com>> 写道：



在现在的版本中，App/PC端可以同步最近播放的500首歌；
我尝试用Fiddler抓包但是没有成功；

**Comment by sylvaner-h** [comment]
我是 win10 + 安卓，我再尝试下；

**Comment by jsososo** [comment]
不过app的接口扒起来有个风险就是他可能用的是私有的编码，那就不太好搞了

2021年1月13日 上午10:21，Sylvaner <notifications@github.com<mailto:notifications@github.com>> 写道：



我是 win10 + 安卓，我再尝试下；
