### ISSUE TITLE
song.js在235行写错了rest api的名称 ，应该是post不是get

### ISSUE THREAD

**Issue by zhoushoujian** [jsososo/QQMusicApi#9]
song.js在235行写错了rest api的名称 ，应该是post不是get

**Comment by jsososo** [comment]
复制了忘改了，感谢指出！

**Comment by zhoushoujian** [comment]
我在本地访问/song/url获取不到vkey，访问/song/urls获取不到purl是因为本地没有cookie吗？

**Comment by jsososo** [comment]
嗯，应该是的，可以用postman请求一下本地的 user/setCookie 接口，或者把 https://api.qq.jsososo.com/user/cookie 这里面的 json 格式的 cookie写到 /data/cookie.json 那个文件里也可以。不过这个 cookie 最近有效期又变成了只有一天

**Comment by zhoushoujian** [comment]
cookie 有效期又变成了只有一天意味着第二天就需要更换cookie，不换就获取不到链接，是这意思吗？

**Comment by jsososo** [comment]
是的，这个属实有点头疼，我也解决不了登陆问题
