### ISSUE TITLE
global对象挂载req/res造成的并发问题

### ISSUE THREAD

**Issue by raphaelsoul** [jsososo/QQMusicApi#95]
https://github.com/jsososo/QQMusicApi/blob/fc84879ed45fa849995d60c7401db80e3082de84/app.js#L58

这样的写法是有并发问题😳

**Comment by jsososo** [comment]
我有注意到这个问题，这里以后肯定会去改的，并且要改成方便 node 直接调用的写法，但是我比较好奇的是为什么我在线上还没有遇到过因为这个写法产生的并发问题，因为线上接口调用量并不小，而且有些接口长列表也确实比较费时，理论上是会出现问题的

2021年2月5日 下午4:46，Dechen Zhuang <notifications@github.com<mailto:notifications@github.com>> 写道：



https://github.com/jsososo/QQMusicApi/blob/fc84879ed45fa849995d60c7401db80e3082de84/app.js#L58

这样的写法是有并发问题😳

**Comment by jsososo** [comment]
已修复
