### ISSUE TITLE
设置cookies后访问还是显示未登录

### ISSUE THREAD

**Issue by seale** [jsososo/QQMusicApi#98]
![image](https://user-images.githubusercontent.com/12511058/108548174-68d9fc80-7326-11eb-8795-532cf9388960.png)
post /user/setCookie 接口后显示操作成功。
get /user/cookie 也有内容返回，不过 uin 那里是空的。
之后访问了用户主页信息返回未登录。

**Comment by mjyhj** [comment]
> ![image](https://user-images.githubusercontent.com/12511058/108548174-68d9fc80-7326-11eb-8795-532cf9388960.png)
> post /user/setCookie 接口后显示操作成功。
> get /user/cookie 也有内容返回，不过 uin 那里是空的。
> 之后访问了用户主页信息返回未登录。

我直接传入不了，请问怎么操作
![2](https://user-images.githubusercontent.com/22577418/109329426-81ea2c80-7895-11eb-9a36-ede4bc200c01.png)

**Comment by jsososo** [comment]
把 app.js 里的 62行的 ownCookie: 1 去掉再试一下，因为共享cookie 现在会带来封号风险，所以我去掉了

**Comment by seale** [comment]
> 把 app.js 里的 62行的 ownCookie: 1 去掉再试一下，因为共享cookie 现在会带来封号风险，所以我去掉了

成功了，感谢

**Comment by kid0510z** [comment]
把这个 写进文档中吧， 我刚找了好久，终于看到这个issues了

**Comment by jsososo** [comment]
是应该理一理文档了，好几个项目的文档都需要更新一下了，害，主要今年来一直都挺忙的

2021年7月1日 下午4:01，King ***@***.******@***.***>> 写道：



把这个 写进文档中吧， 我刚找了好久，终于看到这个issues了

**Comment by kid0510z** [comment]
我最近也在看qq音乐这块，加油！

**Comment by iwxyi** [comment]
现在是在50行，去掉之后 setCookie，然后再调用 /user/cookie，uin 也是空的，调用 refresh 显示未登录

**Comment by ctaoist** [comment]
一样，去掉仍然没有效果
